### ISSUE TITLE
switch networks for connected user

### ISSUE THREAD

**Issue by natonnelier** [walletlink/coinbase-wallet-sdk#257]
I've been going through the docs and the classes in this repo trying to find a way to allow a user switch between networks such as Mainnet, xDai and Arbitrum One, but haven't found such a function. Ideally the user should be able to do it without being disconnected or needing to manually re-connect. 
Is this possible? Could you please point me in the right direction if so?

**Comment by jfrazier-eth** [comment]
Try the following
```ts
const provider = walletLink.makeWeb3Provider(JSON_RPC_URL, CHAIN_ID);

const handleNetworkChange = (chainId: string) => {
  console.log(chainId);
};

provider.on('chainChanged', handleNetworkChange);
```

* The WalletLink provider seems to provide the same interface as a MetaMask provider https://docs.metamask.io/guide/ethereum-provider.html#chainchanged

**Comment by natonnelier** [comment]
thanks @jfrazier-eth but that's just a listener. I need to actually trigger a network switch.

**Comment by natonnelier** [comment]
I tried using the Metamask's `wallet_switchEthereumChain`:
```
window.ethereum
    .request({
      method: 'wallet_switchEthereumChain',
      params: [{ chainId: newChainId }]
    })
```
 but I get the following Error:

```
Error
code: 4001
message: "A request is already in progress"
```

**Comment by jfrazier-eth** [comment]
Ah I see, have you tried this. 
```ts
const chainId = '137'; // polygon
window.walletLinkRelay.switchEthereumChain(chainId);
```
It doesn't seem to be documented but I'm able to get it to prompt me to switch switch networks.

**Comment by natonnelier** [comment]
> Ah I see, have you tried this.
> 
> ```ts
> const chainId = '137'; // polygon
> window.walletLinkRelay.switchEthereumChain(chainId);
> ```
> 
> It doesn't seem to be documented but I'm able to get it to prompt me to switch switch networks.

`window.walletLinkRely` seems to be undefined. Same for `window.ethereum.walletLinkRely`.
Am I missing a library? Should I install/import something?

**Comment by jfrazier-eth** [comment]
I looked into it a little more (actually accepted the network change in my wallet) and it doesn't end up switching the network in the wallet :/ . Should've tested this earlier. 

I was using walletlink@2.4.0

**Comment by brendanww** [comment]
@natonnelier @jfrazier-eth Here is some sample code for how to change networks. Please let me know if that helps.

We implement the EIP-3326 spec, which is best described here
https://eips.ethereum.org/EIPS/eip-3326

```
      const walletlink = new WalletLink({
        appName: 'My Awesome DApp',
        appLogoUrl: 'https://example.com/logo.png',
      })
      
      window.ethereum = walletlink.makeWeb3Provider(
        `https://mainnet.infura.io/v3/{keyHere}`, 1,
      )
      
    await ethereum.request({
      method: 'wallet_switchEthereumChain',
      params: [{
        chainId: '0xA86A',
      }],
    })
```

Worth noting that you can also switch networks by sending an addEthereumChain request per EIP-3085 spec (https://eips.ethereum.org/EIPS/eip-3085). If it is one of our whitelisted networks, we'll treat the request as a `wallet_switchEthereumChain` request. If it not, then we'll currently reject the request. In 2-4 weeks we'll have support for adding non-whitelisted chains via 3085.

Here's a sample 3085 request:

```
    await ethereum.request({
      method: 'wallet_addEthereumChain',
      params: [{
        chainId: '0x89',
        rpcUrls: ['https://polygon-mainnet.infura.io/v3/keyHere'],
        chainName: 'Polygon Mainnet',
        nativeCurrency: { name: 'Matic', decimals: 18, symbol: 'MATIC' },
        blockExplorerUrls: ['https://explorer-mainnet.maticvigil.com'],
        iconUrls: ['https://wallet-api-production.s3.amazonaws.com/uploads/b474d4bf3af389e5f26ed66956f1da8a/maticLogo.png'],
      }],
    })
```
