### ISSUE TITLE
Please, explain purpose of such interface makeWeb3Provider(ETH_JSONRPC_URL)

### ISSUE THREAD

**Issue by 1chtulhu** [walletlink/coinbase-wallet-sdk#286]
To create web3 provider we need to call makeWeb3Provider(and see qr) in such manner:
`walletLink.makeWeb3Provider(ETH_JSONRPC_URL, CHAIN_ID)`

But what the purpose of specifying only one RPC_URL - this parameter is not bind to concrete network. 
If I understand correctly, this is one default ETH_JSONRPC_URL which can handle one specific network in totally unpredictable environment (we cant know which network will be used by dapp user). I can specify `ETH_JSONRPC_URL = 'https://polygon-rpc.com/'`, but user still can connect via rinkeby and what the correct behavior for dapp in this situation? 

**Q: Why walletlink developers create such interface, what logic was?(Possibly I miss something)** 

P.S. I see more logic in walletconnect solution - simply specifying whole mapping of possible rpc endpoints.

**Comment by brendanww** [comment]
@1chtulhu the rpc url you provide to makeWeb3Provider should be the rpcUrl associated with the chainId being passed in. This is the chainId+rpcUrl that dapp is specifying as its default chain+rpcUrl pair.

For other chainId's, the rpcUrl is either provided by Coinbase Wallet if the network is whitelisted or by the dapp via 3085 request. There's no need to pass in additional rpcUrl's as this is what EIP-3085 is for.

For a good example of how to add a network to the wallet via 3085, see https://github.com/sushiswap/sushiswap-interface/blob/0d7470d3d7d532bf2c8d4c2ecac197b251326206/src/modals/NetworkModal/index.tsx#L260

**Comment by 1chtulhu** [comment]
@brendanww Thank you for response. Is Coinbase always returns their rpcUrl for whitelisted networks or can be other cases? And what if I want to use multiple whitelisted networks(in one dapp) why I need no pass my rpcUrl to see modal with qr code?
```
// if true, hide QR code in LinkFlow (which happens if no jsonRpcUrl is provided)
private connectDisabled = false
```

**Comment by brendanww** [comment]
@1chtulhu the rpcUrl is provided by the clients. It's possible a request will come through before the rpcUrl has been set by the clients (eg https://github.com/walletlink/coinbase-wallet-sdk/blob/cd44a7c3410a28080b56bafb60a3af874e7a6b62/js/src/provider/WalletLinkProvider.ts#L669). The rpcUrl provided by the dapp is basically a fallback for that scenario.

**Comment by straightupjac** [comment]
I'm having an issue with walletlink where if I connect with Coinbase wallet via walletlink -- I get a `No jsonRpcUrl provided` error but if I connect with the normal window.ethereum provider then everything works as expected. Is this a related issue? @brendanww

**Comment by brendanww** [comment]
@straightupjac can you clarify what you mean by "I connect with Coinbase wallet via walletlink" in terms of code?

**Comment by straightupjac** [comment]
@brendanww I think I figure out my problem. In the walletlink provider, we have to pass in an RPC url like alchemy or infura in order for smart contract calls to work with the wallet extension right? 

I was using web3-react and didn't include an infura key and it was causing problems but for the injected provider/ window.ethereum connections, I don't need to provide an RPC url and everything just works. Is it possible to make walletlink have a setting such that if its the coinbase extension being connected, we don't need to add the infura key/alchemy key in the config?

**Comment by brendanww** [comment]
@straightupjac You will always need to specify a valid jsonRpcUrl for walletlink to work as intended when instantiating walletlink.
